[tool.poetry]
name = "rag"
version = "0.1.0"
description = ""
authors = ["asmabasly <asmabasly0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain-community = "^0.2.11"
qdrant-client = "^1.10.1"
pypdf2 = "^3.0.1"
langchain-ollama = "^0.1.1"
ragas = "0.0.22"
langchain = "^0.2.12"
langchain-core = "<0.2.29"
langchain-huggingface = "^0.0.3"
pypdf = "^4.3.1"
utils = "^1.0.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
